version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:5672"]
        interval: 30s
        timeout: 10s
        retries: 5

  inventory-service:
    build: ./inventory-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq
    networks:
        - ecommerce-network
    links:
      - "order-service"

  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
        - ecommerce-network

networks:
  ecommerce-network:
    name: ecommerce-network
    driver: bridge