version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - ecommerce-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ecommerce-network

  order-service:
    build: ./order-service
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - rabbitmq
    networks:
        - ecommerce-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "3001:3001"
    depends_on:
      - mongo
      - rabbitmq
    networks:
        - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge